---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/SecurityAudit
      - arn:aws:iam::aws:policy/AmazonInspectorReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::634729597623:root
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: Externalid
  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Dome9Readonly
      Roles:
      - Ref: Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Dome9ReadOnly
          Action:
          - cloudtrail:LookupEvents
          - dynamodb:DescribeTable
          - elasticfilesystem:Describe*
          - elasticache:ListTagsForResource
          - firehose:Describe*
          - firehose:List*
          - guardduty:Get*
          - guardduty:List*
          - kinesis:List*
          - kinesis:Describe*
          - kinesisvideo:Describe*
          - kinesisvideo:List*
          - logs:Describe*
          - logs:Get*
          - logs:FilterLogEvents
          - lambda:List*
          - s3:List*
          - sns:ListSubscriptions
          - sns:ListSubscriptionsByTopic
          - waf-regional:ListResourcesForWebACL
          Effect: Allow
          Resource: "*"
Parameters:
  Externalid:
    Type: String
    Description: Enter Dome9 External ID
Outputs:
  RoleARNID:
    Description: Your Role ARN ID
    Value:
      Fn::GetAtt:
      - Role
      - Arn
  ExternalID:
    Description: Dome9 External ID
    Value:
      Ref: Externalid
