---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/SecurityAudit
      - arn:aws:iam::aws:policy/AmazonInspectorReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::634729597623:root
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: Externalid
  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Dome9Readonly
      Roles:
      - Ref: Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Dome9ReadOnly
          Action:
              - 'cognito-identity:DescribeIdentityPool'
              - 'cognito-idp:DescribeUserPool'
              - 'cognito-idp:DescribeRiskConfiguration'
              - 'dynamodb:ListTagsOfResource'
              - 'ec2:SearchTransitGatewayRoutes'
              - 'elasticfilesystem:Describe*'
              - 'elasticache:ListTagsForResource'
              - 'es:ListTags'
              - 'eks:DescribeNodegroup'
              - 'eks:ListNodegroups'
              - 'glue:GetSecurityConfigurations'
              - 'kinesis:List*'
              - 'kinesis:Describe*'
              - 'kinesisvideo:Describe*'
              - 'kinesisvideo:List*'
              - 'logs:Get*'
              - 'logs:FilterLogEvents'
              - 'mq:DescribeBroker'
              - 'mq:ListBrokers'
              - 'personalize:DescribeDatasetGroup'
              - 'personalize:ListDatasetGroups'
              - 's3:List*'
              - 'secretsmanager:DescribeSecret'
              - 'sns:ListSubscriptions'
              - 'sns:ListTagsForResource'
              - 'states:DescribeStateMachine'
              - 'transcribe:Get*'
              - 'transcribe:List*'
              - 'translate:GetTerminology'
              - 'waf-regional:ListResourcesForWebACL'
              - 'wafv2:ListWebACLs'
              - 'wafv2:ListResourcesForWebACL'
          Effect: Allow
          Resource: "*"
Parameters:
  Externalid:
    Type: String
    Description: Enter Dome9 External ID
Outputs:
  RoleARNID:
    Description: Your Role ARN ID
    Value:
      Fn::GetAtt:
      - Role
      - Arn
  ExternalID:
    Description: Your External ID
    Value:
      Ref: Externalid
